## Python Fundamental Course

## String Variable

In [83]:
Name = "My name is Anamul Hoque Adar"
type(Name)

str

In [84]:
print(Name)

My name is Anamul Hoque Adar


In [85]:
Mess = "We said that, 'Python is powerful'"
type(Mess)

str

In [86]:
print(Mess)

We said that, 'Python is powerful'


In [87]:
if True:
    print(True)

True


## Concate two variables or String

In [88]:
word1 = "Python"
word2 = "Programming"
res = word1+ " " +word2
res

'Python Programming'

## Accessing Variables index

In [89]:
res[0:]

'Python Programming'

## Upper() function to convert value to upper value

In [90]:
res.upper()

'PYTHON PROGRAMMING'

## Strip() function use to trim extra spaces

In [91]:
res.strip()

'Python Programming'

## Checking variable length using len() function

In [92]:
len(res)

18

## Mathematical Operators

In [93]:
x = 5.7
x

5.7

In [94]:
int(x)

5

In [95]:
w = 3 - 7j
type(w)

complex

In [96]:
12/2

6.0

In [97]:
12//2

6

In [98]:
12 **2

144

In [99]:
14%3

2

In [100]:
int(10*2 - 5 + 10 + (12/6)) # 10*2 - 5 + 10 + 2 -> 20 - 5 + 10 + 2 ->20 - 5 + 12

27

In [101]:
2*10 - 5 + 12/7

16.714285714285715

In [102]:
a = 20
b = 10
c = 15
d = 5
e = 0

e = (a / b) * c / d       #( 30 * 15 ) / 5
print("Value of (a + b) * c / d is ",  e)

Value of (a + b) * c / d is  6.0


In [103]:
x = pow(12,2)
x

144

In [104]:
print(f"We are printing the value o x which is {x:.2f}")

We are printing the value o x which is 144.00


In [105]:
num = input("Enter a number")
num

Enter a number10


'10'

In [106]:
name = input("Enter a name")

Enter a nameAnamul


In [107]:
print(name)

Anamul


In [108]:
type(num)
type(name)

str

In [109]:
num1 = int(input("Enter a number"))

Enter a number10


In [110]:
type(num1)

int

## Python Data Structure

##  Creating List
### When you want to collect a mutable ordered list of elements, use a list. (For example, when you want to append new phone numbers to a list: [number1, number2, ...]).
#### List is mutable[Changble]

In [111]:
num_list = [1, 2, 3, 4, 8, 9]
num_list1 = list((1, 2, 3, 4, 8, 9))

In [112]:
type(num_list)
type(num_list1)

list

In [113]:
print(num_list,num_list1)

[1, 2, 3, 4, 8, 9] [1, 2, 3, 4, 8, 9]


In [114]:
num_list2 = [3, 2, [2, 4, 6], 5, 9]

In [115]:
print(num_list2)

[3, 2, [2, 4, 6], 5, 9]


In [116]:
name_list = ["Adar","Jobon","Rakib","Sunny"]

In [117]:
print(name_list)

['Adar', 'Jobon', 'Rakib', 'Sunny']


In [118]:
mixed_list = ["Sourob", True, 1, 1.34, 8+0j]

In [119]:
print(mixed_list)

['Sourob', True, 1, 1.34, (8+0j)]


In [120]:
mixed_list[1:2]

[True]

In [121]:
num_list2

[3, 2, [2, 4, 6], 5, 9]

In [122]:
num_list2[2]

[2, 4, 6]

In [123]:
num_list2[2][:2]

[2, 4]

In [124]:
num_list2.append(10)

In [125]:
print(num_list2)

[3, 2, [2, 4, 6], 5, 9, 10]


In [126]:
num_list2.insert(3, 100)

In [127]:
print(num_list2)

[3, 2, [2, 4, 6], 100, 5, 9, 10]


In [128]:
num_list2.pop()

10

In [129]:
print(num_list2)

[3, 2, [2, 4, 6], 100, 5, 9]


In [130]:
mixed_list

['Sourob', True, 1, 1.34, (8+0j)]

In [131]:
new_list = mixed_list.copy()

In [132]:
mixed_list.clear()

In [133]:
mixed_list

[]

In [134]:
new_list

['Sourob', True, 1, 1.34, (8+0j)]

In [135]:
corors = ["Red", "Yellow", "Meroon"]

In [136]:
color = corors.copy()

In [137]:
color

['Red', 'Yellow', 'Meroon']

In [138]:
color.extend(["Green","Black","Ash"])

In [139]:
color

['Red', 'Yellow', 'Meroon', 'Green', 'Black', 'Ash']

In [140]:
color.append('Purple')

In [141]:
color

['Red', 'Yellow', 'Meroon', 'Green', 'Black', 'Ash', 'Purple']

In [142]:
del corors

In [143]:
color[6] = "Beguni"

In [144]:
color

['Red', 'Yellow', 'Meroon', 'Green', 'Black', 'Ash', 'Beguni']

## Creating Tuple
### When you want to collect an immutable ordered list of elements, use a tuple. (For example, when you want a (name, phone_number) pair that you wish to use as an element in a set, you would need a tuple rather than a list since sets require elements be immutable).
#### Tuple is immutable[unchangble]

In [145]:
tp1 = tuple((10, 20, 30, 40, 50))

In [146]:
tp2 = (5, 10, 15, 20, 25, 30)

In [147]:
type(tp1)

tuple

In [148]:
type(tp2)

tuple

In [149]:
tp1[0:3]

(10, 20, 30)

In [150]:
tp1[-3:]

(30, 40, 50)

In [151]:
tp2[0:3]

(5, 10, 15)

In [152]:
tp2[3] = 100 ## tuple cannot be canged

TypeError: 'tuple' object does not support item assignment

In [ ]:
tp3 = ("Anamul Hoque Adar", 10000, True, 10+0j)

In [ ]:
tp3

In [ ]:
type(tp3)

## Creating Set
### When you want an unordered collection of unique elements, use a set. (For example, when you want the set of all the words used in a document).

In [ ]:
set1 = {10, 20, 30, 40, 50, 60}

In [ ]:
set2 = set({20,90,87, 'Anamul Hoque Adar'})

In [ ]:
set1

In [ ]:
set2

In [ ]:
set('Adar')

## Creating Dictionaries
### When you want a mapping from keys to values, use a dict. (For example, when you want a telephone book which maps names to phone numbers: {'John Smith' : '555-1212'}). Note the keys in a dict are unordered. (If you iterate through a dict (telephone book), the keys (names) may show up in any order).

In [ ]:
dic1 = {"Name": "Anamul Hoque Adar", "Age": 26, "Hometown": "Dhaka"}

In [ ]:
type(dic1)

In [ ]:
dic1

In [ ]:
dic1["Name"]

## Comparision Operator

### + - * / <= >= != ==

In [ ]:
x = 10
y = 20

In [ ]:
x > y

In [ ]:
x < y

In [ ]:
x <= y

In [ ]:
x >= y

In [ ]:
x != y

In [ ]:
x == y

In [ ]:
type(x == y)

## Conditional Statement

In [ ]:
if 15 == 3*5:
    print("Condition Mached")

In [ ]:
if 10 >= 20-5:
    print('Condition Mached')

In [ ]:
x = 10
if x>9:
    print('X grether than 9')
if x<9:
    print('9 grether than x')

In [ ]:
a = 80
b = 90
if a >= b:
    print('A is equal or gretter than b')
elif a <= b:
    print('A is less or equal than b')
else:
    print('Previous condition are invalid')

## While Loop

In [ ]:
x = 1
while x<=7:
    print(x)
    x = x+1

## For loop

In [ ]:
## Using list

list1 = ["Apple", "Orange", "Banana"]
for i in list1:
    print(i)

In [ ]:
## using Tuple
tup1 = ('10', 'Anamul', 2000)
for i in tup1:
    print(i)

In [153]:
## using range() function
for x in range(5):
    print(x)

0
1
2
3
4


In [154]:
for x in range(10, 15):  ## range(20, 30) 20-Starting point, 30-Ending Point
    print(x)

10
11
12
13
14


In [ ]:
for x in range(20, 30, 2): ## range(20, 30, 2) 20-Starting point, 30-Ending Point, 2-increment by
    print(x)

In [155]:
name = input("Enter a String")
for i in name:
    print(i)

Enter a StringJibon
J
i
b
o
n


In [ ]:
name1 = input('Enter a string ')
for i in name1:
    if i == 'o':
        break
    print(i)

In [ ]:
name1 = input('Enter a string ')
for i in name1:
    if i == 'o':
        continue
    print(i)

## Python Built in function

In [ ]:
## Absolute value
abs(-11.5)

In [ ]:
## Max
x = [20,30,5]
print('Max value is: ', max(x))

## Min
x = [20,30,5]
print('Min value is: ', min(x))

## Sum
x = [20,30,5]
print('Sum value is: ', sum(x))

## Zip
x = [20,30,5]
y = ['Apple','Banana']
z = ['Onion', 'Garlic']
print('Zip value is: ', tuple(zip(x,y,z)))

In [ ]:
x = [20,30,5]
y = ['Apple','Banana']
z = ['Onion', 'Garlic']

for i in list(zip(x,y,z)):
    print(i)

In [ ]:
def addition(a, b):
    "This function is use to add 2 numbers. The function has contain two parameter"
    result = a+b
    return result

In [ ]:
addition(10,10)

In [ ]:
help(addition)

## Lambda Function
#### A lambda function is a small anonymous function. A lambda function can take any number of arguments, but can only have one expression. The power of lambda is better shown when you use them as an anonymous function inside another function. Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

In [ ]:
x = lambda a:a * 10
print(x(10))

In [ ]:
sums = lambda a,b : a*b
print(sums(10,3))

In [ ]:
def sums(n):
    res = lambda a : a % n
    return res

In [ ]:
res = sums(4)
print(res(10))

## Password Checking Example

In [156]:
# Password-Checking-Example
password = input("Enter the password")
if password == '123%#$':
    print("Wrong password")
else:
    print("Correct password")


Enter the passwordAdar
Correct password


In [ ]:
for i in range(4):
    password = input("Enter the password")
    if password == '123%#$':
        print("Access Granted")
        break
    print("Wrong Password")
else:
    print("The process is complete! Thanks")

## Array

In [157]:
import array as ar

In [158]:
ar.cars = ['Red','Green','Yellow','Blue','Black']

In [ ]:
for i in ar.cars:
    print(i)

In [159]:
my_list = []
num = int(input("how many numbers you want to input"))
for i in range(num):
    val = int(input('Enter the number'))
    my_list.append(val)
print('All the numbers : ', my_list)

how many numbers you want to input10
Enter the number10
Enter the number20
Enter the number30
Enter the number30
Enter the number40
Enter the number32
Enter the number76
Enter the number65
Enter the number42
Enter the number14
All the numbers :  [10, 20, 30, 30, 40, 32, 76, 65, 42, 14]


In [ ]:
cars = []
num = int(input('how many numbers you want to input'))
for i in range(num):
    val = input('Enter the values')
    cars.append(val)
print('Values : ',cars)
    

In [ ]:
con = []
num = int(input('how many numbers you want to input'))
for i in range(num):
    val = input('Take the values')
    con.append(val)
    print(con)

In [ ]:
2+2

## Working with Numpy
#### When we have to work on Numerical data, we prefer the numpy module.

In [ ]:
pip install numpy

In [1]:
import numpy as np

In [162]:
arr1 = np.array([1,3,5,7,8])

In [163]:
arr1

array([1, 3, 5, 7, 8])

In [ ]:
print(arr1)

In [ ]:
type(np.array([1,3,5,7,8]))

In [ ]:
## Checking numpy version
print(np.__version__)

In [164]:
## Creating 0-D array
arr0d = np.array(100)
print(arr0d)

100


In [165]:
## Cheak the diamension of array 
print(arr0d.ndim)

0


In [ ]:
## Creating 1-D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

In [ ]:
## Check the diamension of Array
print(arr1d.ndim)

In [2]:
## Creating 2-D array
arr2d = np.array([[1, 2, 3, 4], [10, 20, 30, 40]])
print(arr2d)

[[ 1  2  3  4]
 [10 20 30 40]]


In [3]:
## Check the diamension of array
print(arr2d.ndim)

2


In [4]:
## Creating 3-D array
arr3d = np.array([[[10, 20, 30, 40], [8, 4, 8, 3]], [[20, 30, 40,50], [31, 41, 51,61]]])
print(arr3d)

[[[10 20 30 40]
  [ 8  4  8  3]]

 [[20 30 40 50]
  [31 41 51 61]]]


In [5]:
## Check the diamension of array
print(arr3d.ndim)

3


### Access numpy array elements

In [7]:
## 1-D array
arr1 = np.array([10, 20, 90, 99])
print(arr1)

[10 20 90 99]


In [8]:
## Access the elements
arr1[0]

10

In [9]:
arr1[0:3]

array([10, 20, 90])

In [10]:
arr1[-2:]

array([90, 99])

In [11]:
## Add array elements
print(arr1[0] + arr1[3]) ## 10 + 99

109


In [ ]:
## Subtract array elements
print(arr1[3] - arr1[2]) ## 99 - 90

In [166]:
## Access 2-D Array
arr2 = np.array([[10, 70, 30, 15], [89, 20, 45, 65]])
print(arr2)

[[10 70 30 15]
 [89 20 45 65]]


In [167]:
arr2[0,1]

70

In [168]:
## Access 3-D array
arr3 = np.array([[[10, 20, 45, 60],[20, 34, 35, 65]], [[45, 24, 36, 27],[89, 12, 14, 34]]])
print(arr3)

[[[10 20 45 60]
  [20 34 35 65]]

 [[45 24 36 27]
  [89 12 14 34]]]


In [169]:
arr3[0,1,3]

65

### Mathematical Operation with Array

In [ ]:
arr1 = np.array([10, 12, 13, 14])
arr2 = np.ones(4)

In [ ]:
arr1 + arr2

In [ ]:
arr1 * arr2

In [ ]:
arr1 / arr2

### Array Aggregate Function

In [ ]:
arr1.sum()

In [ ]:
arr1.max()

In [ ]:
arr1.min()

In [ ]:
arr10 = np.zeros((3,4), dtype= 'i')
print(arr10)

In [ ]:
arr11 = np.ones((4,5), dtype = 'i')
print(arr11)

In [ ]:
arr11.dtype

### Numpy Array Copy VS View
#### The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [ ]:
arr_sal = np.array((10000, 15000, 20000, 23000, 21000))

In [ ]:
print(arr_sal)

In [ ]:
arrDep = arr_sal.copy()

In [ ]:
print(arrDep)

In [ ]:
print(arrDep)

In [ ]:
arrView = arr_sal.view()

In [ ]:
print(arr_sal)

In [ ]:
print(arrView)

### Array Shape

In [ ]:
arr01 = np.array([[10, 20, 30, 40],[21, 31, 41, 51]])

In [ ]:
print(arr01)

In [ ]:
print(arr01.shape)

In [12]:
arr02 = np.array([1, 2, 3, 4, 5], ndmin=5)

In [13]:
print(arr02)

[[[[[1 2 3 4 5]]]]]


In [ ]:
print(arr02.shape)

### Numpy Array Reshape

In [ ]:
arr101 = np.array([10, 20, 30, 40, 50, 60, 70,80])

In [ ]:
print(arr101)

In [ ]:
arr101.reshape(2, 4)

In [14]:
arr102 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [15]:
print(arr102)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
print(arr102.shape)

(12,)


In [17]:
arr102.reshape(2 ,3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### Array Iterating

In [18]:
arr1001 = np.array([1, 3, 5, 7, 9]) # 1-D Array

for x in arr1001:
    print(x)

1
3
5
7
9


In [19]:
arr1002 = np.array([[10, 13, 15, 17], [21, 23, 24, 25]]) # 2-D Array

for x in arr1002:
    print(x)

[10 13 15 17]
[21 23 24 25]


In [20]:
arr1002 = np.array([[10, 13, 15, 17], [21, 23, 24, 25]]) # 2-D Array

for x in arr1002:
    for i in x:
        print(i)

10
13
15
17
21
23
24
25


In [21]:
arr1003 = np.array([[[[10, 13, 14, 15],[17, 16, 15, 20]], [[21, 32, 43, 54],[20, 30, 40, 50]]]])
print(arr1003)

[[[[10 13 14 15]
   [17 16 15 20]]

  [[21 32 43 54]
   [20 30 40 50]]]]


In [175]:
print(arr1003.shape)

(1, 2, 2, 4)


In [22]:
for x in arr1003:
    for y in x:
        for i in y:
            for j in i:
                print(j)

10
13
14
15
17
16
15
20
21
32
43
54
20
30
40
50


#### In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [23]:
for x in np.nditer(arr1003): 
    print(x)

10
13
14
15
17
16
15
20
21
32
43
54
20
30
40
50


### Array Joining

In [33]:
arr01 = np.array([10, 20, 30]) # 1-D Array
arr02 = np.array([21, 22, 23]) # 1-D Array

# We pass a sequence of arrays that we want to join to the concatenate() function,
# along with the axis. If axis is not explicitly passed, it is taken as 0.

arr03 = np.concatenate((arr01, arr02))
print(arr03)

[10 20 30 21 22 23]


In [30]:
arr03 = np.array([[100, 200, 300], [90, 80, 70]])
arr04 = np.array([[200, 300, 400], [60, 70, 10]])

arr05 = np.concatenate((arr03, arr04))
print(arr05)

[[100 200 300]
 [ 90  80  70]
 [200 300 400]
 [ 60  70  10]]


In [31]:
arr06 = np.concatenate((arr03, arr04), axis = 1)
print(arr06)

[[100 200 300 200 300 400]
 [ 90  80  70  60  70  10]]


In [ ]:
# Using Stack function instead of concatenate function
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

arr07 = np.stack((arr03, arr04))
print(arr07)

In [ ]:
arr07 = np.stack((arr03, arr04),axis = 1)
print(arr07)

### Spliting Numpy Array

In [34]:
arr10 = np.array([10, 20, 30, 40, 50, 60])

In [35]:
print(arr10)

[10 20 30 40 50 60]


In [36]:
new_arr10 = np.array_split(arr10, 3)
print(new_arr10)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [37]:
## Access Spliting Array
print(new_arr10[0])
print(new_arr10[1])
print(new_arr10[2])

[10 20]
[30 40]
[50 60]


In [38]:
## Split the 2-D array
arr2d = np.array([[10, 20], [12, 13], [14,15], [20, 22], [30, 42]])
print(arr2d)

[[10 20]
 [12 13]
 [14 15]
 [20 22]
 [30 42]]


In [39]:
new_arr2d = np.array_split(arr2d, 5)
print(new_arr2d)
print('Áccess the 2nd array')
print(new_arr2d[1])

[array([[10, 20]]), array([[12, 13]]), array([[14, 15]]), array([[20, 22]]), array([[30, 42]])]
Áccess the 2nd array
[[12 13]]


In [41]:
## Split using hsplit fuction
arrHsplit = np.array([[20, 30, 40], [21, 31, 41], [22, 32, 43], [89, 76, 54]])
print(arrHsplit)

[[20 30 40]
 [21 31 41]
 [22 32 43]
 [89 76 54]]


In [42]:
newHsplit = np.hsplit(arrHsplit, 3)
print(newHsplit)

[array([[20],
       [21],
       [22],
       [89]]), array([[30],
       [31],
       [32],
       [76]]), array([[40],
       [41],
       [43],
       [54]])]


In [ ]:
print(newHsplit[0]

### Serching Array

In [ ]:
arrserarch = np.array([1, 2, 5, 6, 7, 9])
x = np.where(arrserarch == 9)
print(x)

In [ ]:
arrserarch = np.array([1, 2, 5, 6, 7, 9])
x = np.where(arrserarch%2 == 0)
print(x)


## Python Pandas

In [ ]:
# Create DataFrame
# A pandas DataFrame can be created using various inputs like −

# Lists
# dict
# Series
# Numpy ndarrays
# Another DataFrame
# DataFrame Structure --> pandas.DataFrame( data, index, columns, dtype, copy)

### Create a empty dataframe

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame()
print(df)

### Create dataframe by List

In [181]:
# Example 01
L1 = ([10, 20, 30, 40])
df1 = pd.DataFrame(L1)
print(df1)

    0
0  10
1  20
2  30
3  40


In [ ]:
# Example 02
L2 = ([['Abir', 20000], ['Jibon', 23000], ['Rahim', 12000], ['Anwar', 34000]])
df2 = pd.DataFrame(L2)
print(df2)

In [ ]:
# Example 02
L2 = ([['Abir', 20000], ['Jibon', 23000], ['Rahim', 12000], ['Anwar', 34000]])
df2 = pd.DataFrame(L2, columns = ['Emp_Name','Salary'])
print(df2)

### Create a DataFrame by Dictionary

In [ ]:
D1 = {'Name' : ['Jibon', 'Akash', 'Riyad', 'Sufol', 'Junayed', 'Akber'],
      'Salary' : [20000, 30000, 10000, 23000, 43000, 25000],
      'Age' : [25, 20, 45, 33, 22, 42]}
dfd1 = pd.DataFrame(D1)
print(dfd1)

### Dataframe column selection

In [ ]:
dfd1[['Name', 'Age']] 

### Add new column into dataframe

In [ ]:
dfd1['Increment_percentage'] = 10

In [ ]:
dfd1

In [ ]:
dfd1['Increment_Sal'] = dfd1['Salary'] + ((dfd1['Salary'] * dfd1['Increment_percentage'])/100)

In [ ]:
dfd1

In [ ]:
dfd1['Year'] = 2022

In [ ]:
dfd1

### Delete a column from dataframe

In [ ]:
del dfd1['Year']

In [ ]:
dfd1

### Insert a new row into dataframe

In [ ]:
## Create a new DataFrame
data = {'name': ['Somu', 'Kiku', 'Amol', 'Lini'],
        'physics': [68, 74, 77, 78],
        'chemistry': [84, 56, 73, 69],
        'algebra': [78, 88, 82, 87]}
print(data)

In [ ]:
df10 = pd.DataFrame(data)
df10

In [ ]:
new_row = {'name': ['Riyaz'], 'physics':75, 'chemistry': 71, 'algebra':50}

In [ ]:
df10 = df10.append(new_row, ignore_index = True)

In [ ]:
df10

In [ ]:
df10['physics'].max()

In [ ]:
df10['physics'].min()

In [ ]:
df10['physics'].sum()

### Delete a row from dataframe

In [ ]:
df10.drop(4) ## Zero is index number

In [ ]:
df_copy = df10.copy()

In [ ]:
df_copy[['name','algebra']].

### Delete missing Value

In [4]:
import pandas as pd
import numpy as np

In [7]:
dic = {'Name': ['Jhon','Edwin','Jacob','Kristian',np.nan],
       'DoB': [pd.NaT, pd.Timestamp('1985-10-10'), pd.Timestamp('1995-10-15'), pd.NaT, pd.NaT],
       'dept': ['HR','Accounts','MIS', np.nan, np.nan],
       'Salary': [20000, 40000, 12000, 35000, 22000]
      }

In [17]:
df = pd.DataFrame(dic)

In [18]:
df

Name        DoB      dept  Salary
0      Jhon        NaT        HR   20000
1     Edwin 1985-10-10  Accounts   40000
2     Jacob 1995-10-15       MIS   12000
3  Kristian        NaT       NaN   35000
4       NaN        NaT       NaN   22000

In [12]:
df.dropna()

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS   12000

In [14]:
df.dropna(inplace = True)

In [15]:
df

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS   12000

In [16]:
del df

In [22]:
df.dropna(how = 'all')

Name        DoB      dept  Salary
0      Jhon        NaT        HR   20000
1     Edwin 1985-10-10  Accounts   40000
2     Jacob 1995-10-15       MIS   12000
3  Kristian        NaT       NaN   35000
4       NaN        NaT       NaN   22000

In [25]:
df.dropna(subset=['dept','DoB'])

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS   12000

In [27]:
df.dropna(thresh=2)

Name        DoB      dept  Salary
0      Jhon        NaT        HR   20000
1     Edwin 1985-10-10  Accounts   40000
2     Jacob 1995-10-15       MIS   12000
3  Kristian        NaT       NaN   35000

In [29]:
df.dropna(how = 'any', inplace = True)

In [30]:
df

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS   12000

In [33]:
df['Salary'].replace(12000, 2000, inplace = True)

In [34]:
df

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS    2000

In [35]:
mean = df['Salary'].mean()

In [37]:
df['Salary'].replace(2000, mean, inplace = True)

In [38]:
df

Name        DoB      dept  Salary
1  Edwin 1985-10-10  Accounts   40000
2  Jacob 1995-10-15       MIS   21000

In [43]:
qs = [10, 20, 30]

In [44]:
type(qs)

list

In [48]:
max(qs)

30

In [49]:
min(qs)

10

In [50]:
sum(qs)

60

In [52]:
import pandas as pd
df = pd.DataFrame(qs)

In [ ]:
qs.